[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_staking = "3RfqbVcgDYvZ9JhVBZyfMpoocqiaLBVEAdb6wyANhRdx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/thomascadle/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
